export const USER_MOBILE_CHANGED = 'USER_MOBILE_CHANGED';
export const USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED';
export const USER_REGISTER_ATTEMP = 'USER_REGISTER_ATTEMP';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';