export const FIRSTNAME_CHANGED = 'FIRSTNAME_CHANGED';
export const  LASTNAME_CHANGED = 'LASTNAME_CHANGED';
export const FATHERNAME_CHANGED = 'FATHERNAME_CHANGED';
export const NATIONALCODE_CHANGED = 'NATIONALCODE_CHANGED';
export const IDNUM_CHANGED='IDNUM_CHANGED';
export const GENDER_CHANGED='GENDER_CHANGE';
export const ADDRESS_CHANGED='ADDRESS_CHANGED';
export const MOBILE_CHANGED='MOBILE_CHANGED';
export const EMAIL_CHANGED='EMAIL_CHANGED';
export const PASSWORD_CHANGED='PASSWORD_CHANGED';
export const TYPEEMPLOYE_CHANGED='TYPEEMPLOYE_CHANGED';
export const DEGRE_CHANGED='DEGRE_CHANGED';
export const  DATALAWYERLICENSE_CHANGED = 'DATALAWYERLICENSE_CHANGED';
export const WORKEXPERIENCE_CHANGED='WORKEXPERIENCE_CHANGED';
export const PHONENUMBER_CHANGED='PHONENUMBER_CHANGED';
export const IMAGE_CHANGED = 'IMAGE_CHANGED';
export const  RESUME_CHANGED = 'RESUME_CHANGED';
export const LAWYERNOTEBOOK_CHANGED = 'LAWYERNOTEBOOK_CHANGED';
export const  LAWYERLICENSE_CHANGED = ' LAWYERLICENSE_CHANGED';
export const LAWER_Register_ATTEMP = 'LAWER_Register_ATTEMP';
export const LAWER_Register_SUCCESS = 'LAWER_Register_SUCCESS';
export const LAWER_Register_FAIL = 'LAWER_Register_FAIL';





