export const MOBILE_CHANGED = 'MOBILE_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const USER_LOGIN_ATTEMP = 'USER_LOGIN_ATTEMP';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_GET_DATA='USER_GET_DATA';